server:
  port: 2525
  servlet:
    context-path: /contacts  
spring:
  datasource:
    password: vijay
    url: jdbc:oracle:thin:@localhost:1521/orcl
    username: vijay
    driver-class-name: oracle.jdbc.driver.OracleDriver 
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  mvc:
    view:
      prefix: /views/
      suffix: .jsp