server:
  port: 2525
  servlet:
    context-path: /user  
spring:
  datasource:
    password: 
    url: jdbc:h2:mem:testdb
    username: sa
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  h2:
    console:
      enabled: true
  mail:
    port: 587
    host: smtp.gmail.com
    username: hibernatejpa@gmail.com
    password: Techies@88
    properties:
      mail:
       smtp:
        auth: true
        connectiontimeout: 10000
        timeout: 10000
        writetimeout: 10000
        starttls:
         enable: true